#!/usr/bin/env bash
#===============================================================================
#
#          FILE: check_mk_setup
# 
#         USAGE: ./check_mk_setup
# 
#   DESCRIPTION: 
# 
#       OPTIONS: ---
#  REQUIREMENTS: Active inetd in TrueNAS - tftp
#          BUGS: ---
#         NOTES: Can be installed wherever you like.
#                Add path of the file to a Start-Script (Post-Boot).
#        AUTHOR: Christopher Bock (cb), christopher@bocki.com
#  ORGANIZATION: 
#       CREATED: 07/17/2018 05:54:02 PM
#       UPDATED: 03/31/2022 00:51:34 AM
#      REVISION: 2.3
#===============================================================================

set -o nounset                              # Treat unset variables as an error

#Change Hostname of OMD-Host here / My default is "status.FQDN"
OMD_HOST="status.$(hostname -d)"
OMD_IP=$(getent hosts "$OMD_HOST" |cut -d\  -f1)
OMD_IP="$OMD_IP, 127.0.0.1"
SCRIPTPATH="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
#SOURCE="https://raw.githubusercontent.com/tribe29/checkMK/master/agents/check_mk_agent.freebsd"
SOURCE="https://YOUR.OMD.HOST/SITENAME/check_mk/agents/check_mk_agent.freebsd"
BIN="check_mk_agent"
BIN_WGET=$(which wget)

#Do we wan't extra plugins?
REPOSITORY='https://YOUR.OMD.HOST/SITENAME/check_mk/agents/plugins/'
PLUGINS=""

$BIN_WGET -q -O "${SCRIPTPATH}/${BIN}" "${SOURCE}"
chmod +x "${SCRIPTPATH}/${BIN}"

INETD_LINE="checkmk stream tcp nowait root $SCRIPTPATH/$BIN check_mk_agent"
SERVICES_LINE='checkmk 6556/tcp #check_mk'
HOSTS_ALLOW="checkmk: $OMD_IP"

grep -qF -- "$INETD_LINE" "/etc/inetd.conf" || echo "$INETD_LINE" >> /etc/inetd.conf
grep -qF -- "$INETD_LINE" "/conf/base/etc/inetd.conf" || echo "$INETD_LINE" >> /conf/base/etc/inetd.conf
grep -qF -- "$SERVICES_LINE" "/conf/base/etc/services" || echo "$SERVICES_LINE" >> /conf/base/etc/services
grep -qF -- "$SERVICES_LINE" "/etc/services" || echo "$SERVICES_LINE" >> /etc/services
grep -qF -- "$HOSTS_ALLOW" "/etc/hosts.allow" || echo "$HOSTS_ALLOW" >> /etc/hosts.allow
grep -qF -- "checkmk: ALL" "/etc/hosts.deny" || echo "checkmk: ALL" >> /etc/hosts.deny

killall -HUP inetd

sed -i '' 's|export MK_LIBDIR="/usr/local/lib/check_mk_agent"|export MK_LIBDIR="'"${SCRIPTPATH}"'/check_mk_plugins"|g' "${SCRIPTPATH}/${BIN}"

for plugin in $PLUGINS;
do
  mkdir -p "${SCRIPTPATH}/check_mk_plugins/plugins"
  $BIN_WGET -q -O "${SCRIPTPATH}/check_mk_plugins/plugins/${plugin}" "${REPOSITORY}/${plugin}"
  chmod +x "${SCRIPTPATH}/check_mk_plugins/plugins/${plugin}"
done
