#!/usr/bin/env bash
#===============================================================================
#
#          FILE: check_mk_setup
# 
#         USAGE: ./check_mk_setup
# 
#   DESCRIPTION: 
# 
#       OPTIONS: ---
#  REQUIREMENTS: Active inetd in TrueNAS - tftp
#          BUGS: ---
#         NOTES: Can be installed wherever you like.
#                Add path of the file to a Start-Script (Post-Boot).
#                Alt. set periodic cronjob for long-running-systems.
#        AUTHOR: Christopher Bock (cb), christopher@bocki.com
#  ORGANIZATION: 
#       CREATED: 07/17/2018 05:54:02 PM
#       UPDATED: 08/16/2024 15:31:34 9M
#      REVISION: 2.7
#===============================================================================

set -o nounset                              # Treat unset variables as an error

OMD_HOST="status.$(hostname -d)"
OMD_IP=$(getent hosts "$OMD_HOST" |cut -d\  -f1)
OMD_CL="127.0.0.1, ${OMD_IP:-}"
SCRIPTPATH="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
SOURCE="https://raw.githubusercontent.com/tribe29/checkMK/master/agents/check_mk_agent.freebsd"
#SOURCE="https://YOUR.OMD.HOST/SITENAME/check_mk/agents/check_mk_agent.freebsd"
BIN="check_mk_agent"

#Do we wan't extra plugins?
#REPOSITORY='https://YOUR.OMD.HOST/SITENAME/check_mk/agents/plugins/'
REPOSITORY='https://raw.githubusercontent.com/tribe29/checkMK/master/agents/plugins/'
PLUGINS=""

# check if wget returns 0
if wget -q -o /dev/null "${source}"; then
  wget -q -o "${scriptpath}/${bin}" "${source}"
  chmod +x "${scriptpath}/${bin}"
fi

INETD_LINE="checkmk stream tcp nowait root $SCRIPTPATH/$BIN check_mk_agent"
SERVICES_LINE="checkmk		6556/tcp   #check_mk_agent"
HOSTS_ALLOW="check_mk_agent: ${OMD_CL}"

grep -qxF -- "$INETD_LINE" "/etc/inetd.conf" || echo "$INETD_LINE" >> /etc/inetd.conf
grep -qxF -- "$INETD_LINE" "/conf/base/etc/inetd.conf" || echo "$INETD_LINE" >> /conf/base/etc/inetd.conf
grep -qxF -- "$SERVICES_LINE" "/conf/base/etc/services" || echo "$SERVICES_LINE" >> /conf/base/etc/services
grep -qxF -- "$SERVICES_LINE" "/etc/services" || echo "$SERVICES_LINE" >> /etc/services
grep -qxF -- "$HOSTS_ALLOW" "/etc/hosts.allow" || echo "$HOSTS_ALLOW" >> /etc/hosts.allow
grep -qxF -- "check_mk_agent: ALL" "/etc/hosts.deny" || echo "check_mk_agent: ALL" >> /etc/hosts.deny

killall -HUP inetd

sed -i '' 's|export MK_LIBDIR="/usr/local/lib/check_mk_agent"|export MK_LIBDIR="'"${SCRIPTPATH}"'/check_mk_plugins"|g' "${SCRIPTPATH}/${BIN}"

for plugin in $PLUGINS;
do
  mkdir -p "${SCRIPTPATH}/check_mk_plugins/plugins"
  $BIN_WGET -q -O "${SCRIPTPATH}/check_mk_plugins/plugins/${plugin}" "${REPOSITORY}/${plugin}"
  chmod +x "${SCRIPTPATH}/check_mk_plugins/plugins/${plugin}"
done

mkdir -p "${SCRIPTPATH}/check_mk_plugins/plugins/3600"
wget https://raw.githubusercontent.com/crpb/checkmk-smart/main/disk_smart_info.py -qO "${SCRIPTPATH}/check_mk_plugins/plugins/3600/disk_smart_info"
chmod +x "${SCRIPTPATH}/check_mk_plugins/plugins/3600/disk_smart_info"

# Insert Cron job
CMKPATH=$(awk '/check_mk_agent/{print$6}' /etc/inetd.conf)
CMKPATH=${CMKPATH%/*}
CRON=$(midclt call cronjob.query |jq '.[]|select(.command|endswith("check_mk_setup"))|.id')
if test -z $CRON; then
  midclt call cronjob.create '{
  "user": "root",
  "command": "'$CMKPATH'/check_mk_setup",
  "description": "checkmk_update",
  "enabled": true,
  "stdout": true,
  "stderr": false,
  "schedule": {
  "minute": "0",
  "hour": "*/6",
  "dom": "*",
  "month": "*",
  "dow": "*"
}}'
fi
